logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%clr(%5level)] [%thread] %clr(%logger{20}.%M){cyan}\(%F:%line\) - %msg%n'

# 根路径配置
server:
  address: 0.0.0.0
  port: 80
  servlet:
    context-path: /


# 自定义属性
web:
  path: /usr/local/static

spring:
  application:
    name: zgame-admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # 静态资源配置
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/resource/,classpath:/public/,file:${web.path}


net:
  id: tankAdmin
  protocol-location: protocol.xml
  registry:
    center: zookeeper
    user:
    password:
    address:
      - 127.0.0.1:2181
  consumer:
    consumers:
      - consumer: tankHomeProvider
        load-balancer: consistent-hash

orm:
  id: mongodbConfig
  entity-package: com.zfoo.tank.admin.**.entity
  host:
    database: tank
    user:
    password:
    address:
      - 127.0.0.1:27017
  caches:
    - strategy: default
      size: 6000
      expire-millisecond: 600000
  persisters:
    - strategy: default
      type: time
      config: 60000

storage:
  id: storageManager
  scan:
    package: com.zfoo.tank.common.**.resource
  resource:
    location: classpath:/excel