# 根路径配置
server:
  address: 0.0.0.0
  port: 9600
  servlet:
    context-path: /


# 自定义属性
web:
  path: /usr/local/static

spring:
  application:
    name: zgame-admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # 静态资源配置
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/resource/,classpath:/public/,file:${web.path}
