server:
  port: 13003


logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%clr(%5level)] [%thread] %clr(%logger{20}.%M){cyan}\(%F:%line\) - %msg%n'


orm:
  id: mongodbConfig
  entity-package: com.zfoo.tank.common.**.entity
  host:
    database: party
    user:
    password:
    address:
      - 127.0.0.1:27017
  caches:
    - strategy: default
      size: 6000
      expire-millisecond: 600000
    - strategy: tenThousand
      size: 10000
      expire-millisecond: 600000
  persisters:
    - strategy: default
      type: time
      config: 60000
    - strategy: cron30s
      type: cron
      config: 0/30 * * * * ?


web:
  connectUrls:
      - 10.59.60.150:14001
      - 10.59.60.150:14001
      - 10.59.60.150:14001
      - 10.59.60.150:14001